spring:
  profiles:
    include: logging,management
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
      spring:
        jackson:
          deserialization:
            fail-on-unknown-properties=true:

# Default port is 8080. This value can be changed.
server:
  port: 8080
